name: network_client
description: A simple Dart package for making network requests with platform-specific support.
version: 1.2.3
homepage: https://github.com/maynul4/netwrokClient

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

example:
  path: lib/network_client/example/
